### PR TITLE
Run jobs concurrently

### PR DESCRIPTION
**Pull request by pierreprinetti**
it's faster!

### CODE REVIEW

**Comment by mandre** [comment]
At first glance this looks good. Did you check that the inserted results are ordered correctly and that there's no "gap" between results, meaning we do not write over existing lines with different IDs?
From memory, I believe it should be ok, just wondering if you checked that the implementation of the function returning the line number is solid in a multithreaded environment...

**Comment by pierreprinetti** [comment]
tried this morning. There are issues with skipped rows, but on top of that...

```
2020/03/02 08:58:55 googleapi: Error 429: Quota exceeded for quota group 'WriteGroup' and limit 'Write requests per user per 100 seconds' of service 'sheets.googleapis.com' for consumer 'project_number:1019279456336'., rateLimitExceeded
```

we're too good for Google

**Comment by mandre** [comment]
Or we could try to rate limit the writes to gsheets if it's simple enough? Otherwise I agree with you, it's not worth the trouble. We can just let gazelle run in the background or take a break while it's running :coffee:

**Comment by pierreprinetti** [comment]
yeah let's vote :coffee: for now :grin:

**Pull request closed without merging**
