### PR TITLE
Update the nightly job names too

### PR DESCRIPTION
**Pull request by EmilienM**
Sorry I forgot them...

### CODE REVIEW

**Comment by pierreprinetti** [comment]
```
 ./cireport
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.10-e2e-openstack-kuryr
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.10-e2e-openstack-parallel
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.10-e2e-openstack-parallel 1468522994618863616
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/shiftstack/gazelle/pkg/gsheets.(*Sheet).getAllIDs(0xc0005f1e40)
	/var/home/pierre/code/src/github.com/shiftstack/gazelle/pkg/gsheets/sheet.go:113 +0x308
github.com/shiftstack/gazelle/pkg/gsheets.(*Sheet).getIndex(0xc0005f1e40, 0x14613de20ec01000)
	/var/home/pierre/code/src/github.com/shiftstack/gazelle/pkg/gsheets/sheet.go:126 +0x2e
github.com/shiftstack/gazelle/pkg/gsheets.(*Sheet).AddRow(0xc0005f1e40, {{0xac2aa6, 0x4e}, {0xc0006a4120, 0x13}, {0xc0001e06c8, 0x7}, {0xc0003fc4c0, 0x3, 0x4}, ...}, ...)
	/var/home/pierre/code/src/github.com/shiftstack/gazelle/pkg/gsheets/sheet.go:167 +0x88
main.main()
	/var/home/pierre/code/src/github.com/shiftstack/gazelle/cmd/cireport/main.go:119 +0x2e5
```

**Comment by EmilienM** [comment]
@pierreprinetti fixed it, an empty row was in the spreadsheet. I removed it and now the tool works fine.

**Comment by EmilienM** [comment]
```
./cireport
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.10-e2e-openstack-kuryr
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.10-e2e-openstack-parallel
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.10-e2e-openstack-serial
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.10-upgrade-from-stable-4.9-e2e-openstack-upgrade
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.10-e2e-openstack-ovn
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.10-e2e-openstack-fips
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.10-e2e-openstack-az
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.10-e2e-openstack-proxy
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.9-e2e-openstack-proxy
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.9-e2e-openstack-kuryr
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.9-e2e-openstack-parallel
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.9-e2e-openstack-serial
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.9-upgrade-from-stable-4.8-e2e-openstack-upgrade
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.9-e2e-openstack-ovn
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.9-e2e-openstack-az
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.9-e2e-openstack-fips
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.8-e2e-openstack-kuryr
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.8-e2e-openstack-parallel
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.8-e2e-openstack-serial
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.8-e2e-openstack-serial 1468523007113695232
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.8-e2e-openstack-serial 1468885474641711104
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.8-e2e-openstack-serial 1469247971311751168
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.8-e2e-openstack-serial 1469610534591533056
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.8-e2e-openstack-serial 1469972930673774592
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.8-e2e-openstack-serial 1470335320049324032
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.8-e2e-openstack-serial 1470697729070993408
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.8-e2e-openstack-serial 1471060224923144192
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.7-e2e-openstack-kuryr
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.7-e2e-openstack-kuryr 1470634827513335808
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.7-e2e-openstack-parallel
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.7-e2e-openstack-serial
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.7-e2e-openstack-serial 1468523003850526720
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.7-e2e-openstack-serial 1469247969625640960
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.7-e2e-openstack-serial 1469972928991858688
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.7-e2e-openstack-serial 1470697727389077504
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.6-e2e-openstack-parallel
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.6-e2e-openstack-parallel 1468522999635251200
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.6-e2e-openstack-parallel 1469247967109058560
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.6-e2e-openstack-parallel 1469972926466887680
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.6-e2e-openstack-parallel 1470697724893466624
Updating periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.6-e2e-openstack-serial
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.6-e2e-openstack-serial 1468523000482500608
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.6-e2e-openstack-serial 1469247967994056704
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.6-e2e-openstack-serial 1469972927305748480
periodic-ci-shiftstack-shiftstack-ci-main-periodic-4.6-e2e-openstack-serial 1470697725723938816
Updating release-openshift-ocp-installer-e2e-openstack-4.5
Updating release-openshift-ocp-installer-e2e-openstack-serial-4.5
```

**Comment by pierreprinetti** [comment]
/lgtm
Thanks! All good, that's @mandre's fault :P

**Pull request merged**
