### PR TITLE
Non monotonic

### PR DESCRIPTION
**Pull request by pierreprinetti**
Prior to this patch, job IDs were assumed to be increasing
monotonically. This assumption recently proved wrong.

Please note that the `-id` command line flag is now only accepting one job ID.

### CODE REVIEW

**Comment by mandre** [comment]
The previous implementation knew to ignore pending jobs -- is it possible to restore the same behavior?

**Comment by pierreprinetti** [comment]
oh yeah - and I just found out how to do it.

**Comment by pierreprinetti** [comment]
@mandre PTAL

**Comment by pierreprinetti** [comment]
(squashed)

**Review by mandre — APPROVED** [review]

**Pull request merged**
